import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from '../styles/index.module.scss'
import Navbar from "../components/Navbar.js";
import Bridge from "../public/BRIDGE.jpg";
import Blob from "../components/svj1.js";
import Blob1 from "../components/svg1.js";
import Blob2 from "../components/svg2.js";
import Blob3 from "../components/svg3.js";
import Blob4 from "../components/svg4.js";
import Blob5 from "../components/svg5.js";
import Blob6 from "../components/svg6.js";
import Login from "../components/login.js"
import {useStripe, useElements, CardElement} from '@stripe/react-stripe-js';

export default function Home() {
  const stripe = useStripe();
  const elements = useElements();
  return (
    <div className={styles.container}>
      <Head>
        <title>BRIDGE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" user-scalable="no" />

      </Head>
     <Navbar className={styles.navbar}/>
     
     <section className={styles.hero}>
       <Image  src={Bridge} 
       layout="fill" alt="" priority="true" className={styles.image}/>
       <div className={styles.blob}>
       <Blob /></div>
       <div className={styles.blob1}>
       <Blob1 /></div>
       <div className={styles.leftblob}>
       <p>Are you an <b>Entrepreneur</b><br/>looking for 
       an investor to fund you or <br/>
      help you in <b>expanding and growing</b><br/>
      your business?
 </p></div>
 <div className={styles.rightblob}>
       <p>Are you an <span><b>Investor</b></span><br/>
          looking for 
       good businesses,startups <br/>
      or ideas to <b>invest</b> in?
      
 </p></div>
 <div className={styles.blob2}>
       <Blob2 /></div>
       
     </section>
     <section className={styles.second}>
       <div className={styles.first}>
         <div className={styles.content}>
           <p>Here at <b>Bridge</b > we make it possible and easy for both investors and entrepreneurs to collaborate in <b>growing and scaling</b> businesses.</p>
         </div>
         <div className={styles.blob3}>
       <Blob3 /></div>

       </div>
       <div className={styles.contentRight}>
         <p>
           <span><b>P</b></span>itch your idea or business and get funded.
         </p>
         <div className={styles.blob4}>
       <Blob4 /></div>
       </div>
<div className={styles.contentMiddle}>
  <div className={styles.contentHolder}>
    <p><span><b>Not</b></span>  a member?</p>
    <div className={styles.blob5}>
       <Blob5 /></div>
       <Link href="/Signup"><a><b>Sign</b> up</a></Link>
  </div>
  
</div>
     </section>
     <section className={styles.plans}>
     <div className={styles.blob6}>
       <Blob6 /></div>
       <section className={styles.pricing}>
         <h1>Investor</h1>
         <div className={styles.investor}>
           <div className={styles.card}>
             <h1 id={styles.bronze}>Bronze</h1>
             <h2>$ 2</h2>
             <ul>
               <li>5 pitches daily</li>
               <li>Plus 1 bonus pitch</li>
               <li><s>Free trial</s></li>
             </ul>


           </div>
           <div className={styles.card}>
           <h1 id={styles.silver} >Silver</h1>
             <h2>$ 5</h2>
             <ul>
               <li>10 pitches daily</li>
               <li>2 bonus pitch daily</li>
               <li><s>Free trial</s></li>
             
            </ul>
           </div>
           <div className={styles.card}>
           <h1 id={styles.gold}>Gold</h1>
             <h2><span>$</span> 10</h2>
             <ul>
              <li>Unlimited pitches daily</li>
               <li>Push notification feature</li>
               <li>1 month free trial</li>
             
            </ul>

           </div>

         </div>
         <h1 id={styles.entre}>Entreprenuer</h1>
         <div className={styles.entreprenuer}>

         <div className={styles.cardEntreprenuer}>
           <h1>$ 2</h1>
           <h2>Pay a <b>one time</b> fee during registration and get a lifetime acces to post as many pitches as you wish now and in the future</h2>
             

             </div>
         </div>

         

       </section>
   

      



     </section> 
         


      
     
    </div>
  )
}
